version: "3.8"
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
  course-service:
    build: ./course-service
    ports:
      - "5001:5000"
  forum-service:
    build: ./forum-service
    ports:
      - "5002:5000"
  profile-service:
    build: ./profile-service
    ports:
      - "5003:5000"
  progress-service:
    build: ./progress-service
    ports:
      - "5004:5000"
  video-service:
    build: ./video-service
    ports:
      - "5005:5000"
  watchlist-service:
    build: ./watchlist-service
    ports:
      - "5006:5000"
