version: "3.8"

services:
  auth-service:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
    container_name: auth-service
    ports:
      - "5000:5000"
    environment:
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Users"
    networks:
      - app-network

  course-service:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/course-service:latest
    container_name: course-service
    ports:
      - "5001:5000"
    environment:
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Courses"
    networks:
      - app-network

  forum-service:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/forum-service:latest
    container_name: forum-service
    ports:
      - "5002:5000"
    environment:
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Discussions"
    networks:
      - app-network

  profile-service:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/profile-service:latest
    container_name: profile-service
    ports:
      - "5003:5000"
    environment:
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "UserProfiles"
      AUTH_SERVICE_URL: "http://auth-service:5000"
    networks:
      - app-network

  progress-service:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/progress-service:latest
    container_name: progress-service
    ports:
      - "5004:5000"
    environment:
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Progress"
    networks:
      - app-network

  video-service:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/video-service:latest
    container_name: video-service
    ports:
      - "5005:5000"
    environment:
      AWS_REGION: "us-east-1"
      S3_BUCKET_NAME: "dread-project-videos-bucket-2615473"
      DYNAMODB_TABLE: "Videos"
    networks:
      - app-network

  watchlist-service:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/watchlist-service:latest
    container_name: watchlist-service
    ports:
      - "5006:5000"
    environment:
      AWS_REGION: "us-east-1"
      DYNAMODB_TABLE: "Watchlist"
    networks:
      - app-network

  frontend:
    image: 303553230681.dkr.ecr.us-east-1.amazonaws.com/frontend-service:latest
    container_name: frontend-service
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
